// Task 12.15 — lists every `#[tauri::command]` `tauri_commands::invoke_handler()` registers
// (`src/tauri_commands.rs`) so `tauri-build` autogenerates an `allow-<command>`/`deny-<command>`
// ACL permission pair for each one (Tauri v2's per-command capability system — see
// `capabilities/default.json`, which references these exact autogenerated identifiers). Without
// this list, `AppManifest::commands` defaults to empty and *no* app-defined command would ever be
// invokable from the WebView, regardless of what a capability file grants (Tauri v2: "no capability
// = no access to the IPC layer"). Keep this list in lockstep with
// `tauri_commands::invoke_handler()`'s own `tauri::generate_handler![...]` list — a command missing
// from either fails closed (denied), never silently open.
fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "account_create",
            "account_load",
            "account_get",
            "contact_add",
            "contact_list",
            "contact_rename",
            "contact_block",
            "contact_mark_verified",
            "contact_acknowledge_key_change",
            "contact_answer_request",
            "session_connect",
            "session_get",
            "session_close",
            "chat_send",
            "pump_once",
            "file_send",
        ]),
    ))
    .expect("failed to run tauri-build (see build.rs)");
}
